/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    EmergencyBanner: typeof import('./src/components/EmergencyBanner.vue')['default']
    HamburgerMenuButton: typeof import('./src/components/HamburgerMenuButton.vue')['default']
    HeaderContainer: typeof import('./src/components/HeaderContainer.vue')['default']
    InputText: typeof import('./src/components/InputText.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    MenuListBox: typeof import('./src/components/MenuListBox.vue')['default']
    MobileMenu: typeof import('./src/components/MobileMenu.vue')['default']
    NotificationBanner: typeof import('./src/components/NotificationBanner.vue')['default']
    RadioButton: typeof import('./src/components/RadioButton.vue')['default']
    Selectbox: typeof import('./src/components/Selectbox.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    UtilityLink: typeof import('./src/components/UtilityLink.vue')['default']
  }
}
