/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    InputText: typeof import('./src/components/InputText.vue')['default']
    NotificationBanner: typeof import('./src/components/NotificationBanner.vue')['default']
    RadioButton: typeof import('./src/components/RadioButton.vue')['default']
    Selectbox: typeof import('./src/components/Selectbox.vue')['default']
    SFCsample: typeof import('./src/components/SFCsample.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    UtilityLink: typeof import('./src/components/UtilityLink.vue')['default']
  }
}
